Zad1 - front-end
karienne/patronage pull request #1
Opened 2021-11-26 16:56 UTC by karienne

@lukasz-galka @alexsimkovich

2021-11-26 19:07 UTC, alexsimkovich requested changes

2021-11-26 19:07 UTC, alexsimkovich commented on main.js
> +url = 'https://raw.githubusercontent.com/alexsimkovich/patronage/main/api/data.json';
proszę poprawnie zdefiniować zmienną

2021-11-26 19:07 UTC, alexsimkovich commented on main.js
> +
można to usprawnić, np. użyć https://developer.mozilla.org/pl/docs/Web/API/Element/insertAdjacentHTML

```
function appendData(data) {
    const column1 = document.getElementById("col1");

    data.forEach(item => {
        productsInCart.push({ 'inCart': 0 })
        column1.insertAdjacentHTML('afterbegin', `
          <div class='product'>
            <img src='${item.image}' class='product-image' />
            <h3 class='title-product'>${item.title}</h3>
            <h3 class='price-product'>${item.price.toFixed(2)}</h3>
            <h3 class='ingredients-product'>${item.ingredients.join(', ')}</h3>
            <a class='add-cart cart-button'>Zamów</a>
          </div>
    `)
    })
}
```

2021-11-26 19:07 UTC, alexsimkovich commented on main.js
> +    let column1 = document.getElementById("col1");
to jest `const`

2021-11-26 19:07 UTC, alexsimkovich commented on main.js
> +    let cart = document.getElementById("col2");
proszę przeczytać czym się różnią let od const. Naprzykład https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/

2021-11-26 19:07 UTC, alexsimkovich commented on main.js
> +        let sum = document.getElementById("tpn");
Też bym sugerował pójść w stronę https://developer.mozilla.org/pl/docs/Web/API/Element/insertAdjacentHTML

2021-11-27 13:54 UTC, lukasz-galka commented on index.html
> +            <div class="products-list" id="col1">
`col1` i `col2` nie sa dobrymi nazwami dla id, nadaj bardziej opisowe id

2021-11-27 13:54 UTC, lukasz-galka commented on main.js
> +    else if(inCartItems == 0 && !emptyCart){
emptyCard moze byc caly czas w htmlu, nadaj na rodzica klase ktora mowi czy koszyk jest pusty i na jej podstawie schowaj/pokaz ten napis

2021-11-27 13:54 UTC, lukasz-galka commented on main.js
> +    let total = document.getElementById("tp"); //koszt zamówienia
`col2`, `tp` - nadaj bardziej opisowe `id`

2021-11-27 13:54 UTC, lukasz-galka commented on main.js
> +    let index = product.id - 1;
nie mozesz zalozyć ze `id` ktore dostajesz w api zawsze bedą po kolei, z czasem jakas pizza moze byc skasowana i wtedy dostaniesz id np `1 2 4...`

2021-11-27 13:54 UTC, lukasz-galka commented on main.js
> +    if (productsInCart[index].inCart == 0){
skorzystaj z `===`

2021-11-27 13:54 UTC, lukasz-galka commented on main.js
> +        button = document.createElement("a");
to `button` czy `link` ?

2021-11-27 13:54 UTC, lukasz-galka commented on main.js
> +        totalPriceTitle.innerHTML = "Koszt zamówienia: ";
takie elementy powinny byc od razy w htmlu i tylko powinnas je chowac/pokazywac jak koszyk jest pusty lub nie poprzez dodanie odpowiedniej klasy

2021-11-29 12:45 UTC, karienne commented on main.js
> +    let index = product.id - 1;
dziękuję za sugestię :) czy jest zatem jakiś sposób bym mogła dodać kolejny parametr (inCart) do każdego produktu w bazie, tak bym nie musiała tworzyć dodatkowej tablicy przechowującej informacje czy produkt jest w koszyku i w jakiej ilości?

2021-12-08 22:22 UTC, merged